#!/bin/bash --login
# **********************************************************
my_name="fatashi2"
# **********************************************************
function print_blue()
{
  echo  -e '\E[1;34m'"$1"'\E[1m\E[0m'
}

function print_warn()
{
  echo  -e '\E[1;32m'"$1"'\E[1m\E[0m'
}

function print_err()
{
  echo  -e '\E[1;31m'"$my_name: OOPS .. $1"'\E[1m\E[0m'
}

# **********************************************************
DSA_DICT="dsa_dictionary.txt"
TUKI_DICT="tuki_kamusi.txt"
# **********************************************************
# -javaagent:/snap/intellij-idea-community/232/lib/idea_rt.jar=37957:/snap/intellij-idea-community/232/bin -Dfile.encoding=UTF-8 -classpath /home/daudi/IdeaProjects/FatashiLinux/out/production/FatashiLinux:/home/daudi/.local/share/JetBrains/IdeaIC2020.1/Kotlin/kotlinc/lib/kotlin-stdlib.jar:/home/daudi/.local/share/JetBrains/IdeaIC2020.1/Kotlin/kotlinc/lib/kotlin-reflect.jar:/home/daudi/.local/share/JetBrains/IdeaIC2020.1/Kotlin/kotlinc/lib/kotlin-test.jar:/home/daudi/.local/share/JetBrains/IdeaIC2020.1/Kotlin/kotlinc/lib/kotlin-stdlib-jdk7.jar:/home/daudi/.local/share/JetBrains/IdeaIC2020.1/Kotlin/kotlinc/lib/kotlin-stdlib-jdk8.jar:/home/daudi/IdeaProjects/FatashiLinux/lib/gson-2.8.6.jar:/home/daudi/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar Fatashi.FatashimainKt 
JAR_PATH="out/artifacts/FatashiLinux_jar"
APP_PATH="/home/daudi/IdeaProjects/FatashiLinux"
cd $APP_PATH

/home/daudi/.jdks/openjdk-14.0.1/bin/java -jar $APP_PATH/$JAR_PATH/FatashiLinux.jar  "-v -p"

# **********************************************************

